# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RobJDavey
author: Robert Davey
email: robert@robjdavey.com
description: > # this means to ignore newlines until "baseurl:"
  A site about software development using the Swift language, and other tech related things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robjdavey.com" # the base hostname & protocol for your site
twitter_username: robjdavey
keybase_username: robjdavey

# Build settings
markdown: kramdown
gems: [jekyll-gist]
